# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=13)),
                ('tipo', models.IntegerField(choices=[('1', 'Bibliotecário'), ('2', 'Usuário')], default='2')),
            ],
        ),
    ]
