# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlebib', '0002_auto_20171110_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('DIS', 'Disponível'), ('EMP', 'Emprestado')], default='DIS', max_length=3),
        ),
    ]
