# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlebib', '0006_auto_20171110_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de dataDevolucao'),
        ),
    ]
