# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlebib', '0007_auto_20171110_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='codEmprestimo',
            field=models.IntegerField(default=0, verbose_name='Código do Empréstimo'),
        ),
    ]
